title: Godfrey Huang's Blog
email: jeanimator@gmail.com
description: >-
  I'm a full-stack software developer, currently focused on modern front-end
  technologies. I'm using React to build my latest projects, and I'm loving it!
  If you are looking for a passionate dev to join your team send me an email or
  a DM!
baseurl: ''
url: ''
twitter_username: jeanimator
github_username: jeanim
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-admin
